### ISSUE TITLE
Deploying a Kubernetes svc breaks when you have the connector running

### ISSUE THREAD

**Issue by lachie83** [Azure/aci-connector-k8s#48]
Looks like the LB provider code for Azure tries to attach a nodePort per node and this breaks when the aci-connector is installed. See event log below.

```
Name:           go-web
Namespace:      default
Labels:         app=go-web
Annotations:        <none>
Selector:       run=go-web
Type:           LoadBalancer
IP:         10.0.209.150
Port:           <unset>   8080/TCP
NodePort:       <unset>   31848/TCP
Endpoints:      10.244.0.12:8080,10.244.1.195:8080,10.244.2.157:8080
Session Affinity:   None
Events:
  FirstSeen LastSeen    Count   From            SubObjectPath   Type        Reason              Message
  --------- --------    -----   ----            -------------   --------    ------              -------
  46m       6m      14  service-controller          Warning     CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service default/go-web: ensure(default/go-web): lb(briar-k8s-demomgmt) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/aci-connector' under resource group 'briar-k8s-demo' was not found.\""
  3m        3m      1   service-controller          Normal      Type                LoadBalancer -> NodePort
  3m        3m      1   service-controller          Normal      DeletingLoadBalancer        Deleting load balancer
  2m        2m      1   service-controller          Normal      Type                NodePort -> LoadBalancer
  49m       39s     15  service-controller          Normal      CreatingLoadBalancer        Creating load balancer
  39s       39s     1   service-controller          Normal      DeletedLoadBalancer     Deleted load 
```

**Comment by chzbrgr71** [comment]
FWIW, I tried creating the service BEFORE the aci-connector was in place. Then adding aci-connector. So far, they both are co-existing.

**Comment by seglauf** [comment]
Same as #30 ?

**Comment by rbitia** [comment]
kubectl get no -o jsonpath='{range.items[*].status.addresses[?(@.type=="ExternalIP")]}{.address}
This also returns nothing when I've deployed a nginx pod

**Comment by lachie83** [comment]
@seglauf I believe this potentially is the same issue.

**Comment by JetPac33** [comment]
Deleting the aci-connector from the cluster will also resolve this issue.

**Comment by seglauf** [comment]
Problem is still unsolved. Wenn i try to expose a service the service will never get an external IP.

F:\k8s\nginx>kubectl get service -l run=my-nginx -o wide
NAME       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE       SELECTOR
my-nginx   10.0.244.128   <pending>     80:30541/TCP   4m        run=my-nginx

**Comment by rbitia** [comment]
The current work around is to deploy a svc before adding the connector or deleting the connector.
